//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTFBLOG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uye
    {
        public Uye()
        {
            this.Makale = new HashSet<Makale>();
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int UyeId { get; set; }
        public string KullaniciAdi { get; set; }
        public string Email { get; set; }
        public string Sifre { get; set; }
        public string AdSoyad { get; set; }
        public string Foto { get; set; }
        public Nullable<int> YetkiId { get; set; }
    
        public virtual ICollection<Makale> Makale { get; set; }
        public virtual Yetki Yetki { get; set; }
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
