//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTFBLOG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetki
    {
        public Yetki()
        {
            this.Uye = new HashSet<Uye>();
        }
    
        public int YetkiId { get; set; }
        public string Yetki1 { get; set; }
    
        public virtual ICollection<Uye> Uye { get; set; }
    }
}
